-- AlterTable
ALTER TABLE "Goal" ADD COLUMN     "targetCarbs" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "targetFat" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "targetProtein" INTEGER NOT NULL DEFAULT 0;
